# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {E:/VGA/Final Project 371/Week12Demo.cache/wt} [current_project]
set_property parent.project_path {E:/VGA/Final Project 371/Week12Demo.xpr} [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
set_property ip_output_repo {e:/VGA/Final Project 371/Week12Demo.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {E:/VGA/Final Project 371/Week12Demo.srcs/sources_1/new/CoinDisplay.vhd}
  {E:/VGA/Final Project 371/Week12Demo.srcs/sources_1/new/CoinDisplay2.vhd}
  {E:/VGA/Final Project 371/Week12Demo.srcs/sources_1/new/CoinDisplay3.vhd}
  {E:/VGA/Final Project 371/Week12Demo.srcs/sources_1/new/CoinDisplay4.vhd}
  {E:/VGA/Final Project 371/Week12Demo.srcs/sources_1/new/CoinDisplay5.vhd}
  {E:/VGA/Final Project 371/Week12Demo.srcs/sources_1/new/CoinDisplay6.vhd}
  {E:/VGA/Final Project 371/Week12Demo.srcs/sources_1/new/CoinDisplay7.vhd}
  {E:/VGA/Final Project 371/Week12Demo.srcs/sources_1/new/CoinDisplay8.vhd}
  {E:/VGA/Final Project 371/Week12Demo.srcs/sources_1/new/CoinDisplay9.vhd}
  {E:/VGA/Final Project 371/ConverterXY.vhd}
  {E:/VGA/Final Project 371/MouseDisplay.vhd}
  E:/OverlayCtl.vhd
  {E:/VGA/Final Project 371/Score_Display.vhd}
  {E:/VGA/Final Project 371/VgaForMouseOnly.vhd}
  {E:/VGA/Final Project 371/Week12Demo.srcs/sources_1/new/WhiteBox.vhd}
  {E:/VGA/Final Project 371/debounce.vhd}
  {E:/VGA/Final Project 371/ps2keyboardXYCoords.vhd}
  {E:/VGA/Final Project 371/Nexys4DdrUserDemo_OptimizedAbdallah.vhd}
}
read_ip -quiet {{E:/VGA/Final Project 371/Week12Demo.srcs/sources_1/ip/ClkGen/ClkGen.xci}}
set_property used_in_implementation false [get_files -all {{e:/VGA/Final Project 371/Week12Demo.srcs/sources_1/ip/ClkGen/ClkGen_board.xdc}}]
set_property used_in_implementation false [get_files -all {{e:/VGA/Final Project 371/Week12Demo.srcs/sources_1/ip/ClkGen/ClkGen.xdc}}]
set_property used_in_implementation false [get_files -all {{e:/VGA/Final Project 371/Week12Demo.srcs/sources_1/ip/ClkGen/ClkGen_ooc.xdc}}]
set_property is_locked true [get_files {{E:/VGA/Final Project 371/Week12Demo.srcs/sources_1/ip/ClkGen/ClkGen.xci}}]

read_ip -quiet {{E:/VGA/Final Project 371/Week12Demo.srcs/sources_1/ip/PxlClkGen/PxlClkGen.xci}}
set_property used_in_implementation false [get_files -all {{e:/VGA/Final Project 371/Week12Demo.srcs/sources_1/ip/PxlClkGen/PxlClkGen_board.xdc}}]
set_property used_in_implementation false [get_files -all {{e:/VGA/Final Project 371/Week12Demo.srcs/sources_1/ip/PxlClkGen/PxlClkGen.xdc}}]
set_property used_in_implementation false [get_files -all {{e:/VGA/Final Project 371/Week12Demo.srcs/sources_1/ip/PxlClkGen/PxlClkGen_late.xdc}}]
set_property used_in_implementation false [get_files -all {{e:/VGA/Final Project 371/Week12Demo.srcs/sources_1/ip/PxlClkGen/PxlClkGen_ooc.xdc}}]
set_property is_locked true [get_files {{E:/VGA/Final Project 371/Week12Demo.srcs/sources_1/ip/PxlClkGen/PxlClkGen.xci}}]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{E:/VGA/Final Project 371/Nexys4DDR_C.xdc}}
set_property used_in_implementation false [get_files {{E:/VGA/Final Project 371/Nexys4DDR_C.xdc}}]


synth_design -top Nexys4DdrUserDemo_optimizedAbdallah -part xc7a100tcsg324-1 -flatten_hierarchy none -directive RuntimeOptimized -fsm_extraction off


write_checkpoint -force -noxdef Nexys4DdrUserDemo_optimizedAbdallah.dcp

catch { report_utilization -file Nexys4DdrUserDemo_optimizedAbdallah_utilization_synth.rpt -pb Nexys4DdrUserDemo_optimizedAbdallah_utilization_synth.pb }
